SUBROUTINE FIND_NEIGHBOURS1 (JLAT, JLON, YDGRID, YDN1)

INTEGER (KIND=JPIM),  INTENT (IN)  :: JLAT, JLON 
TYPE (GRID_t),        INTENT (IN)  :: YDGRID
TYPE (NEIGHBOURS1_t), INTENT (OUT) :: YDN1 

INTEGER (KIND=JPIM) :: IR, IQ, ILOEN, ILOEN1, ILOEN2
INTEGER (KIND=JPIM) :: INUM, IDEN 
INTEGER (KIND=JPIM) :: JLAT1, JLON1, JLAT2, JLON2

INTEGER (KIND=JPIM) :: INORM, KLO, KLOEN
INORM (KLO, KLOEN) = 1 + MODULO (KLO-1, KLOEN)


YDN1%JLON (JIDX___) = INORM (JLON+0, YDGRID%NLOEN (JLAT)); YDN1%JLAT (JIDX___) = JLAT 
YDN1%JLON (JIDX__W) = INORM (JLON-1, YDGRID%NLOEN (JLAT)); YDN1%JLAT (JIDX__W) = JLAT 
YDN1%JLON (JIDX__E) = INORM (JLON+1, YDGRID%NLOEN (JLAT)); YDN1%JLAT (JIDX__E) = JLAT 

IF (JLAT == 1) THEN 
  ILOEN = YDGRID%NLOEN (JLAT)
  IQ = JLON + ILOEN / 2; IR = MODULO (ILOEN, 2)
  IF (IR == 0) THEN 
    YDN1%JLON (JIDX_NW) = INORM (IQ+1, ILOEN ); YDN1%JLAT (JIDX_NW) = JLAT 
    YDN1%JLON (JIDX_N_) = INORM (IQ+0, ILOEN ); YDN1%JLAT (JIDX_N_) = JLAT 
    YDN1%JLON (JIDX_NE) = INORM (IQ-1, ILOEN ); YDN1%JLAT (JIDX_NE) = JLAT 
  ELSE 
    YDN1%JLON (JIDX_NW) = INORM (IQ+1, ILOEN ); YDN1%JLAT (JIDX_NW) = JLAT 
    YDN1%JLON (JIDX_NE) = INORM (IQ+0, ILOEN ); YDN1%JLAT (JIDX_NE) = JLAT 
  ENDIF
ELSE
  JLON1 = JLON 
  JLAT1 = JLAT     ; ILOEN1 = YDGRID%NLOEN (JLAT1)
  JLAT2 = JLAT - 1 ; ILOEN2 = YDGRID%NLOEN (JLAT2)
  INUM = ILOEN1 - ILOEN2 + JLON1 * ILOEN2; IDEN = ILOEN1
  IQ   = INUM / IDEN; IR = (IQ - 1) * ILOEN1 - (JLON1 - 1) * ILOEN2
  IF (IR == 0) THEN 
    YDN1%JLON (JIDX_NW) = INORM (IQ-1, ILOEN2); YDN1%JLAT (JIDX_NW) = JLAT2
    YDN1%JLON (JIDX_N_) = INORM (IQ+0, ILOEN2); YDN1%JLAT (JIDX_N_) = JLAT2
    YDN1%JLON (JIDX_NE) = INORM (IQ+1, ILOEN2); YDN1%JLAT (JIDX_NE) = JLAT2
  ELSE 
    YDN1%JLON (JIDX_NW) = INORM (IQ+0, ILOEN2); YDN1%JLAT (JIDX_NW) = JLAT2
    YDN1%JLON (JIDX_NE) = INORM (IQ+1, ILOEN2); YDN1%JLAT (JIDX_NE) = JLAT2
  ENDIF
ENDIF

IF (JLAT == YDGRID%NDGLG) THEN 
  ILOEN = YDGRID%NLOEN (JLAT)
  IQ = JLON + ILOEN / 2; IR = MODULO (ILOEN, 2)
  IF (IR == 0) THEN 
    YDN1%JLON (JIDX_SW) = INORM (IQ+1, ILOEN ); YDN1%JLAT (JIDX_SW) = JLAT 
    YDN1%JLON (JIDX_S_) = INORM (IQ+0, ILOEN ); YDN1%JLAT (JIDX_S_) = JLAT 
    YDN1%JLON (JIDX_SE) = INORM (IQ-1, ILOEN ); YDN1%JLAT (JIDX_SE) = JLAT 
  ELSE 
    YDN1%JLON (JIDX_SW) = INORM (IQ+1, ILOEN ); YDN1%JLAT (JIDX_SW) = JLAT 
    YDN1%JLON (JIDX_SE) = INORM (IQ+0, ILOEN ); YDN1%JLAT (JIDX_SE) = JLAT 
  ENDIF
ELSE
  JLON1 = JLON 
  JLAT1 = JLAT     ; ILOEN1 = YDGRID%NLOEN (JLAT1)
  JLAT2 = JLAT + 1 ; ILOEN2 = YDGRID%NLOEN (JLAT2)
  INUM = ILOEN1 - ILOEN2 + JLON1 * ILOEN2; IDEN = ILOEN1
  IQ   = INUM / IDEN; IR = (IQ - 1) * ILOEN1 - (JLON1 - 1) * ILOEN2
  IF (IR == 0) THEN 
    YDN1%JLON (JIDX_SW) = INORM (IQ-1, ILOEN2); YDN1%JLAT (JIDX_SW) = JLAT2
    YDN1%JLON (JIDX_S_) = INORM (IQ+0, ILOEN2); YDN1%JLAT (JIDX_S_) = JLAT2
    YDN1%JLON (JIDX_SE) = INORM (IQ+1, ILOEN2); YDN1%JLAT (JIDX_SE) = JLAT2
  ELSE 
    YDN1%JLON (JIDX_SW) = INORM (IQ+0, ILOEN2); YDN1%JLAT (JIDX_SW) = JLAT2
    YDN1%JLON (JIDX_SE) = INORM (IQ+1, ILOEN2); YDN1%JLAT (JIDX_SE) = JLAT2
  ENDIF
ENDIF

END SUBROUTINE FIND_NEIGHBOURS1

